#!/usr/bin/env python3
"""Offline RAGAS evaluation against a running local API.

Usage:
  1. Start the API:  uvicorn api.main:app --reload --port 8000
  2. Run:            python scripts/evaluate.py

Writes scripts/eval_results.json and scripts/EVAL_REPORT.md
"""

from __future__ import annotations

import asyncio
import json
import sys
from pathlib import Path

import httpx

from api.core.constants import EVAL_API_URL

ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "eval_data.json"
RESULTS_PATH = ROOT / "eval_results.json"
REPORT_PATH = ROOT / "EVAL_REPORT.md"


async def collect_sse_answer(client: httpx.AsyncClient, question: str, doc_names=None) -> dict:
    payload = {"query": question}
    if doc_names:
        payload["doc_names"] = doc_names

    answer_parts: list[str] = []
    citations: list[dict] = []
    faithfulness = None

    async with client.stream("POST", EVAL_API_URL, json=payload, timeout=180.0) as response:
        response.raise_for_status()
        async for line in response.aiter_lines():
            if not line or not line.startswith("data:"):
                continue
            raw = line[len("data:"):].strip()
            if not raw:
                continue
            try:
                event = json.loads(raw)
            except json.JSONDecodeError:
                continue
            etype = event.get("type")
            if etype == "token":
                answer_parts.append(event.get("content") or "")
            elif etype == "citations":
                citations = event.get("chunks") or []
            elif etype == "faithfulness":
                faithfulness = event
            elif etype == "done":
                break

    contexts = [c.get("text", "") for c in citations if c.get("text")]
    return {
        "answer": "".join(answer_parts).strip(),
        "contexts": contexts,
        "faithfulness_event": faithfulness,
    }


async def run_cases(cases: list[dict]) -> list[dict]:
    rows = []
    async with httpx.AsyncClient() as client:
        for i, case in enumerate(cases, start=1):
            print(f"[{i}/{len(cases)}] {case['question'][:80]}...")
            try:
                result = await collect_sse_answer(
                    client, case["question"], case.get("doc_names")
                )
                rows.append({
                    "question": case["question"],
                    "ground_truth": case["ground_truth"],
                    "answer": result["answer"],
                    "contexts": result["contexts"],
                    "category": case.get("category"),
                    "error": None,
                })
            except Exception as exc:
                print(f"  ERROR: {exc}")
                rows.append({
                    "question": case["question"],
                    "ground_truth": case["ground_truth"],
                    "answer": "",
                    "contexts": [],
                    "category": case.get("category"),
                    "error": str(exc),
                })
    return rows


def run_ragas(rows: list[dict]) -> dict:
    try:
        from datasets import Dataset
        from ragas import evaluate
        from ragas.metrics import (
            answer_correctness,
            answer_relevancy,
            context_precision,
            context_recall,
            faithfulness,
        )
    except ImportError as exc:
        print(f"RAGAS import failed: {exc}")
        return {"error": str(exc), "note": "Install evaluation deps: pip install ragas datasets"}

    usable = [r for r in rows if r["answer"] and r["contexts"] and not r["error"]]
    if not usable:
        return {"error": "No usable rows with answer+contexts for RAGAS"}

    dataset = Dataset.from_dict({
        "question": [r["question"] for r in usable],
        "answer": [r["answer"] for r in usable],
        "contexts": [r["contexts"] for r in usable],
        "ground_truth": [r["ground_truth"] for r in usable],
    })

    result = evaluate(
        dataset,
        metrics=[
            faithfulness,
            answer_relevancy,
            context_precision,
            context_recall,
            answer_correctness,
        ],
    )
    # ragas Result supports to_pandas / dict-like access depending on version
    try:
        scores = dict(result)
    except Exception:
        scores = {"raw": str(result)}
    return {"n_evaluated": len(usable), "scores": scores}


def write_report(rows: list[dict], ragas_result: dict) -> None:
    scores = ragas_result.get("scores") or {}
    lines = [
        "# Clinical RAG Evaluation Report",
        "",
        "Generated by `scripts/evaluate.py`.",
        "",
        "## Metrics",
        "",
        "| Metric | Score |",
        "|---|---|",
    ]
    for key in (
        "faithfulness",
        "answer_relevancy",
        "context_precision",
        "context_recall",
        "answer_correctness",
    ):
        val = scores.get(key, "—")
        if isinstance(val, float):
            val = f"{val:.4f}"
        lines.append(f"| {key} | {val} |")

    if ragas_result.get("error"):
        lines.extend(["", f"**Note:** {ragas_result['error']}"])

    lines.extend(["", "## Per-case summary", ""])
    for r in rows:
        status = "OK" if r["answer"] and not r["error"] else f"FAIL ({r.get('error')})"
        lines.append(f"- **{r.get('category', 'case')}**: {r['question'][:100]} — {status}")

    REPORT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


async def main() -> int:
    cases = json.loads(DATA_PATH.read_text(encoding="utf-8"))
    rows = await run_cases(cases)
    ragas_result = run_ragas(rows)
    payload = {"rows": rows, "ragas": ragas_result}
    RESULTS_PATH.write_text(json.dumps(payload, indent=2), encoding="utf-8")
    write_report(rows, ragas_result)
    print(json.dumps(ragas_result, indent=2, default=str))
    print(f"Wrote {RESULTS_PATH}")
    print(f"Wrote {REPORT_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(asyncio.run(main()))
